from domain.value_objects.apa_structure import APASectionType
from domain.value_objects.document_blueprint import BLUEPRINTS
from domain.value_objects.document_type import DocumentType

SECTION_GUIDANCE: dict[tuple[DocumentType, APASectionType], str] = {
    (DocumentType.REPORT, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.REPORT,
        APASectionType.INDEX,
    ): "Table of contents generated by the application.",
    (
        DocumentType.REPORT,
        APASectionType.INTRODUCTION,
    ): "Introduce the subject, scope, and purpose.",
    (
        DocumentType.REPORT,
        APASectionType.BODY,
    ): "Develop the report with thematic subheadings.",
    (
        DocumentType.REPORT,
        APASectionType.CONCLUSION,
    ): "Conclude from the source-supported analysis without new facts.",
    (DocumentType.REPORT, APASectionType.SOURCES): "APA 7 references.",
    (DocumentType.RESEARCH, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.RESEARCH,
        APASectionType.INDEX,
    ): "Table of contents generated by the application.",
    (
        DocumentType.RESEARCH,
        APASectionType.ABSTRACT,
    ): "One paragraph of about 150-250 words covering the problem, "
    "scope, findings, and conclusion.",
    (
        DocumentType.RESEARCH,
        APASectionType.INTRODUCTION,
    ): "Explain context, problem, guiding question or objective, and scope.",
    (
        DocumentType.RESEARCH,
        APASectionType.THEORETICAL_FRAMEWORK,
    ): "Explain concepts and background taken from the sources, with "
    "citations.",
    (
        DocumentType.RESEARCH,
        APASectionType.METHODOLOGY,
    ): "Describe only a documentary review of the provided sources: their "
    "number and kinds and how they were analyzed. Never invent fieldwork, "
    "samples, or procedures.",
    (
        DocumentType.RESEARCH,
        APASectionType.BODY,
    ): "Develop and analyze themes with heading-2 and heading-3 subheadings.",
    (
        DocumentType.RESEARCH,
        APASectionType.DISCUSSION,
    ): "Contrast agreements, gaps, and limitations across sources. Add no "
    "new claims.",
    (
        DocumentType.RESEARCH,
        APASectionType.CONCLUSION,
    ): "Answer the guiding question without introducing new information.",
    (DocumentType.RESEARCH, APASectionType.SOURCES): "APA 7 references.",
}


def guidance_for(document_type: DocumentType) -> str:
    blueprint = BLUEPRINTS[document_type]
    lines = []
    for spec in blueprint.sections:
        requirement = "required" if spec.required else "optional"
        guidance = SECTION_GUIDANCE[(document_type, spec.section_type)]
        lines.append(
            f"- {spec.section_type.value} ({requirement}): {guidance}"
        )
    return "\n".join(lines)
