from domain.value_objects.apa_structure import APASectionType
from domain.value_objects.document_blueprint import BLUEPRINTS
from domain.value_objects.document_type import DocumentType

SECTION_GUIDANCE: dict[tuple[DocumentType, APASectionType], str] = {
    (DocumentType.REPORT, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.REPORT,
        APASectionType.INDEX,
    ): "Table of contents generated by the application.",
    (
        DocumentType.REPORT,
        APASectionType.INTRODUCTION,
    ): "Introduce the subject, scope, and purpose.",
    (
        DocumentType.REPORT,
        APASectionType.BODY,
    ): "Develop the report with thematic subheadings.",
    (
        DocumentType.REPORT,
        APASectionType.CONCLUSION,
    ): "Conclude from the source-supported analysis without new facts.",
    (DocumentType.REPORT, APASectionType.SOURCES): "APA 7 references.",
    (DocumentType.RESEARCH, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.RESEARCH,
        APASectionType.INDEX,
    ): "Table of contents generated by the application.",
    (
        DocumentType.RESEARCH,
        APASectionType.ABSTRACT,
    ): "One paragraph of about 150-250 words covering the problem, "
    "scope, findings, and conclusion.",
    (
        DocumentType.RESEARCH,
        APASectionType.INTRODUCTION,
    ): "Explain context, problem, guiding question or objective, and scope.",
    (
        DocumentType.RESEARCH,
        APASectionType.THEORETICAL_FRAMEWORK,
    ): "Explain concepts and background taken from the sources, with "
    "citations.",
    (
        DocumentType.RESEARCH,
        APASectionType.METHODOLOGY,
    ): "Describe only a documentary review of the provided sources: their "
    "number and kinds and how they were analyzed. Never invent fieldwork, "
    "samples, or procedures.",
    (
        DocumentType.RESEARCH,
        APASectionType.BODY,
    ): "Develop and analyze themes with heading-2 and heading-3 subheadings.",
    (
        DocumentType.RESEARCH,
        APASectionType.DISCUSSION,
    ): "Contrast agreements, gaps, and limitations across sources. Add no "
    "new claims.",
    (
        DocumentType.RESEARCH,
        APASectionType.CONCLUSION,
    ): "Answer the guiding question without introducing new information.",
    (DocumentType.RESEARCH, APASectionType.SOURCES): "APA 7 references.",
    (DocumentType.SUMMARY, APASectionType.PRESENTATION): "Compact header.",
    (
        DocumentType.SUMMARY,
        APASectionType.KEY_POINTS,
    ): "List three to seven key points.",
    (
        DocumentType.SUMMARY,
        APASectionType.BODY,
    ): "Write a faithful, shorter prose summary without personal opinion.",
    (DocumentType.SUMMARY, APASectionType.SOURCES): "APA 7 references.",
    (DocumentType.SYNTHESIS, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.SYNTHESIS,
        APASectionType.INTRODUCTION,
    ): "State the topic and the criterion used to integrate the sources.",
    (
        DocumentType.SYNTHESIS,
        APASectionType.BODY,
    ): "Organize by theme rather than by source, showing agreements, "
    "contrasts, and gaps. A comparison table may be used.",
    (
        DocumentType.SYNTHESIS,
        APASectionType.CONCLUSION,
    ): "Conclude the integrated source-supported analysis without new facts.",
    (DocumentType.SYNTHESIS, APASectionType.SOURCES): "APA 7 references.",
    (DocumentType.BRIEF, APASectionType.PRESENTATION): "Title page.",
    (
        DocumentType.BRIEF,
        APASectionType.KEY_POINTS,
    ): "Write a concise executive summary oriented to a decision.",
    (
        DocumentType.BRIEF,
        APASectionType.BODY,
    ): "Cover context, implications, trade-offs, and limits without "
    "repeating KEY_POINTS. KEY_POINTS must state decision implications, "
    "not merely restate descriptive content.",
    (
        DocumentType.BRIEF,
        APASectionType.RECOMMENDATIONS,
    ): "Use a numbered list. Every recommendation must include a citation "
    "to the source supporting its underlying claim and must not introduce "
    "an unsupported action or outcome; otherwise omit this section.",
    (DocumentType.BRIEF, APASectionType.SOURCES): "APA 7 references.",
}


def guidance_for(document_type: DocumentType) -> str:
    blueprint = BLUEPRINTS[document_type]
    lines = []
    for spec in blueprint.sections:
        requirement = "required" if spec.required else "optional"
        guidance = SECTION_GUIDANCE[(document_type, spec.section_type)]
        lines.append(
            f"- {spec.section_type.value} ({requirement}): {guidance}"
        )
    return "\n".join(lines)
